# Generated by Django 5.0.4 on 2024-05-09 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='person',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='work.person', verbose_name='Персона'),
        ),
    ]
