# Generated by Django 5.0.4 on 2024-05-11 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('work', '0004_alter_contract_contract_type_delete_contracttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='pasport',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='work.pasport', verbose_name='Паспорт'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='insurance_object_content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.contenttype', verbose_name='Вид объека (субъекта) страхования'),
        ),
        migrations.AlterField(
            model_name='personinsurance',
            name='pasport',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='work.pasport', verbose_name='Паспорт'),
        ),
    ]
