# Generated by Django 5.0.4 on 2024-05-11 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('work', '0005_alter_client_pasport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='insurance_object_content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(('app_label', 'work'), models.Q(('model', 'house'), ('model', 'personinsurance'), _connector='OR')), on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.contenttype', verbose_name='Вид объека (субъекта) страхования'),
        ),
    ]
