# Generated by Django 5.0.4 on 2024-05-11 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0006_alter_contract_insurance_object_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_type',
            field=models.CharField(choices=[('house', 'Страхование недвижимости'), ('personinsurance', 'Страхование жизни')], verbose_name='Тип договора'),
        ),
    ]
