# Generated by Django 5.0.4 on 2024-05-11 18:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0007_alter_contract_contract_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='scan_doc_owner',
            field=models.FileField(upload_to='scans/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'PDF'], 'Поддерждиваются только PDF файлы', 400)], verbose_name='Скан документа на владение'),
        ),
        migrations.AlterField(
            model_name='house',
            name='scan_tech_plan',
            field=models.FileField(upload_to='scans/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'PDF'], 'Поддерждиваются только PDF файлы', 400)], verbose_name='Скан технического плана'),
        ),
    ]
