# Generated by Django 5.0.4 on 2024-05-11 19:29

import datetime
import django.core.validators
import work.util
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0008_alter_house_scan_doc_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='cost',
            field=models.DecimalField(decimal_places=4, max_digits=20, validators=[django.core.validators.MinValueValidator(0, 'Стоимость договора слишком мала')], verbose_name='Стоимость договора'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='date_created',
            field=work.util.ModelDateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='insuranceSum',
            field=models.DecimalField(decimal_places=4, max_digits=20, validators=[django.core.validators.MinValueValidator(100, 'Страховая сумма слишком мала')], verbose_name='Страховая сумма'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='scan',
            field=models.FileField(upload_to='pasport/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'PDF'], 'Поддерждиваются только PDF файлы', 400)], verbose_name='Скан договора'),
        ),
        migrations.AlterField(
            model_name='incidentdecision',
            name='datetime_of_decision',
            field=work.util.ModelDateField(auto_now_add=True, verbose_name='Дата принятия решения'),
        ),
        migrations.AlterField(
            model_name='incidentdecision',
            name='sum',
            field=models.DecimalField(decimal_places=4, max_digits=20, verbose_name='Сумма страховой выплаты'),
        ),
        migrations.AlterField(
            model_name='pasport',
            name='date_of_issue',
            field=work.util.ModelDateField(validators=[django.core.validators.MaxValueValidator(datetime.date.today, 'Дата выдачи не может быть больше текущего дня')], verbose_name='Дата выдачи'),
        ),
        migrations.AlterField(
            model_name='pasport',
            name='number',
            field=models.IntegerField(validators=[django.core.validators.RegexValidator('\\d{6}', 'Номер указан неверно')], verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='pasport',
            name='series',
            field=models.SmallIntegerField(validators=[django.core.validators.RegexValidator('\\d{4}', 'Серия указана неверно')], verbose_name='Серия'),
        ),
        migrations.AlterField(
            model_name='pasport',
            name='who_issued_code',
            field=models.IntegerField(validators=[django.core.validators.RegexValidator('\\d{6}', 'Код подразделения должен быть 6-значным')], verbose_name='Код подразделения'),
        ),
        migrations.AlterField(
            model_name='person',
            name='date_of_birth',
            field=work.util.ModelDateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='ticketincident',
            name='date_created',
            field=work.util.ModelDateField(auto_now_add=True, verbose_name='Дата создания заявки'),
        ),
    ]
