# Generated by Django 5.0.4 on 2024-05-12 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0009_alter_contract_cost_alter_contract_date_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='insuranceSum',
            new_name='insurance_sum',
        ),
    ]
