# Generated by Django 5.0.4 on 2024-05-14 15:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0011_alter_contract_cost_alter_contract_insurance_sum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='scan',
            field=models.FileField(blank=True, null=True, upload_to='pasport/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'PDF'], 'Поддерждиваются только PDF файлы', 400)], verbose_name='Скан договора'),
        ),
    ]
