# Generated by Django 5.0.4 on 2024-05-16 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0012_alter_contract_scan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketincident',
            name='decision',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='work.incidentdecision'),
        ),
    ]
