# Generated by Django 5.0.4 on 2024-05-17 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0013_alter_ticketincident_decision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('active', 'Активный'), ('active', 'Расторжен'), ('active', 'Наступил страховой случай')], verbose_name='Статус'),
        ),
        migrations.AlterModelTable(
            name='client',
            table='client',
        ),
        migrations.AlterModelTable(
            name='contract',
            table='contract',
        ),
        migrations.AlterModelTable(
            name='employee',
            table='employee',
        ),
        migrations.AlterModelTable(
            name='house',
            table='house',
        ),
        migrations.AlterModelTable(
            name='incidentdecision',
            table='incidentdecision',
        ),
        migrations.AlterModelTable(
            name='pasport',
            table='pasport',
        ),
        migrations.AlterModelTable(
            name='person',
            table='person',
        ),
        migrations.AlterModelTable(
            name='personinsurance',
            table='personinsurance',
        ),
        migrations.AlterModelTable(
            name='ticketincident',
            table='ticketincident',
        ),
        migrations.DeleteModel(
            name='ContractStatus',
        ),
    ]
